
runtime: custom
#runtime_config:
#  jdk: openjdk11
#inbound_services:
#- warmup
#derived_file_type:
#- java_precompiled
#threadsafe: True
#auto_id_policy: default
#api_version: '1.0'
#
#handlers:
#- url: /.*
env: flex
resources:
  cpu: 1
  memory_gb: 4.0
  disk_size_gb: 10.0
#  volumes:
#    - name: ramdisk1
#      volume_type: tmpfs
#      size_gb: 0.5


#skip-files:
#  - app.yaml
#  - target/appengine-staging/WEB-INF/lib/staqnford-corenlp-3.9.2-models.jar

handlers:
  - url: /static
    static_dir: /

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto