#!/usr/bin/env bash

gcloud builds submit --tag gcr.io/bubble-277622/bubble-python-api
gcloud run deploy bubble-python-api --image gcr.io/bubble-277622/bubble-python-api --platform managed --timeout=15m --memory=2Gi --region=us-east1