runtime: java11
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
api_version: 'user_defined'
handlers:
- url: /.*
  script: unused
  login: optional
  secure: optional
skip_files: app.yaml, target/appengine-staging/WEB-INF/lib/stanford-corenlp-3.9.2-models.jar